project:
  name: my-cfn-infra
  regions:
    - us-east-1 # Bạn có thể đổi region
  tests:
    vpc-test:
      template: infrastructure.yaml
      parameters:
        - VpcCIDR: 10.0.0.0/16
        - PublicSubnetCIDR: 10.0.1.0/24
        - PrivateSubnetCIDR: 10.0.2.0/24
        - InstanceType: t3.medium
        - KeyName: my-keypair-name
