version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install cfn-lint taskcat
  pre_build:
    commands:
      - echo "Linting CloudFormation template..."
      - cfn-lint infrastructure.yaml
      - echo "Running Taskcat tests..."
      - taskcat test run
  build:
    commands:
      - echo "Build phase (optional, nothing here)"
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - "**/*"
