version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install cfn-lint taskcat
  pre_build:
    commands:
      - cfn-lint infrastructure.yaml
      - taskcat test run
  build:
    commands:
      - echo "Build phase complete"
  post_build:
    commands:
      - echo "Done"

artifacts:
  files:
    - "**/*"
