name: 'CloudFormation Deploy'

on:
  workflow_dispatch:

permissions: read-all

jobs:
  cfn-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: 'us-east-1'
      STACK_NAME: 'my-cfn-infra-stack'
      TEMPLATE_FILE: 'infrastructure.yaml'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Lint CloudFormation Template
        run: cfn-lint ${{ env.TEMPLATE_FILE }}

      - name: Validate CloudFormation Template on AWS
        run: |
          aws cloudformation validate-template --template-body file://${{ env.TEMPLATE_FILE }}

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file $TEMPLATE_FILE \
            --region $AWS_REGION \
            --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
