name: 'CloudFormation Destroy'

on:
  workflow_dispatch:

permissions: read-all

jobs:
  cfn-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: 'us-east-1'
      STACK_NAME: 'my-cfn-infra-stack'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete CloudFormation Stack
        run: |
          aws cloudformation delete-stack \
            --stack-name $STACK_NAME \
            --region $AWS_REGION
